version: "3.8"

services:
  portfolio-app:
    image: node:21-slim
    command: sh -c "yarn install && yarn start"
    privileged: true
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    environment:
      FAST_REFRESH: false
    volumes:
      - type: bind
        source: .
        target: /app
  